<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by Asep Mabrur (KITech) -->
<wsdl:description targetNamespace="http://new.webservice.namespace" xmlns:wsdl="http://www.w3.org/ns/wsdl" xmlns:wsoap="http://www.w3.org/ns/wsdl/soap" xmlns:whttp="http://www.w3.org/ns/wsdl/http" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://new.webservice.namespace">
	<wsdl:types>
		<xs:schema targetNamespace="http://new.webservice.namespace" elementFormDefault="qualified">
			<xs:element name="NewMessageRequest" type="xs:string"/>
			<xs:element name="NewMessageResponse" type="xs:string"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:interface name="MEStoWEB">
		<wsdl:operation name="MEStoWEB" pattern="http://www.w3.org/ns/wsdl/in-only">
			<wsdl:input messageLabel="In" element="tns:NewMessageRequest"/>
		</wsdl:operation>
	</wsdl:interface>
	<wsdl:binding name="NewBinding" interface="tns:MEStoWEB" type="http://www.w3.org/ns/wsdl/soap" wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">
		<wsdl:operation ref="tns:MEStoWEB" wsoap:mep="http://www.w3.org/2003/05/soap/mep/request-response/"/>
	</wsdl:binding>
	<wsdl:service name="NewService" interface="tns:MEStoWEB">
		<wsdl:endpoint name="NewEndpoint" binding="tns:NewBinding"/>
	</wsdl:service>
</wsdl:description>
